# Generated by Django 6.0.5 on 2026-05-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
                ('plate', models.CharField(max_length=20, verbose_name='Гос. номер')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('fuel_rate', models.FloatField(verbose_name='Норма расхода (л/км)')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО водителя')),
                ('cars', models.ManyToManyField(blank=True, to='fleet.car', verbose_name='Автомобили')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Время выезда')),
                ('return_time', models.DateTimeField(verbose_name='Время заезда')),
                ('start_mileage', models.FloatField(verbose_name='Начальный километраж')),
                ('end_mileage', models.FloatField(verbose_name='Конечный километраж')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.car', verbose_name='Автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver', verbose_name='Водитель')),
            ],
        ),
    ]
