# Generated by Django 6.0.4 on 2026-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('work_phone', models.CharField(max_length=20, verbose_name='Рабочий телефон')),
                ('personal_phone', models.CharField(max_length=20, verbose_name='Личный телефон')),
            ],
        ),
    ]
