# Generated by Django 6.0.5 on 2026-05-23 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SalaryAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начислено')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата начисления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Начисление зарплаты',
                'verbose_name_plural': 'Начисления зарплаты',
            },
        ),
    ]
