# Generated by Django 6.0.3 on 2026-03-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12, verbose_name='Кредитный лимит'),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Текущий счет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Текущий долг'),
        ),
        migrations.AlterField(
            model_name='client',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Всего покупок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безнал'), ('credit', 'Кредит'), ('barter', 'Бартер'), ('mutual', 'Взаимозачет')], max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
