# Generated by Django 6.0.4 on 2026-04-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя поля')),
                ('label', models.CharField(max_length=100, verbose_name='Отображаемое имя')),
                ('field_type', models.CharField(choices=[('string', 'Строка'), ('number', 'Число'), ('date', 'Дата')], max_length=10, verbose_name='Тип')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Передавать')),
                ('precision', models.IntegerField(blank=True, default=2, null=True, verbose_name='Точность (для чисел)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
