# Generated by Django 6.0.3 on 2026-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение параметра')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
