# Generated by Django 6.0.4 on 2026-04-25 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код контрагента')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое наименование')),
                ('inn', models.CharField(help_text='10 или 12 цифр', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10}$|^\\d{12}$', '10 или 12 цифр')], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_marked_for_deletion', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
    ]
