# Generated by Django 6.0.5 on 2026-05-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='Назначение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
